
package org.example.helloworld;

import javax.jws.WebService;
import javax.xml.ws.BindingType;
import java.math.*;
import java.util.Random;


/**
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.5
 * Generated source version: 2.1
 * 
 */
@WebService(portName = "HelloWorldSOAP", serviceName = "HelloWorld", targetNamespace = "http://www.example.org/HelloWorld/", wsdlLocation = "/wsdls/HelloWorld.wsdl", endpointInterface = "org.example.helloworld.HelloWorld")
@BindingType("http://schemas.xmlsoap.org/wsdl/soap/http")
public class HelloWorld_HelloWorldSOAPImpl
    implements HelloWorld
{


    public HelloWorld_HelloWorldSOAPImpl() {
    }

    /**
     * 
     * @param in
     * @return
     *     returns java.lang.String
     */
    public String helloWorld(String in) {
        //replace with your impl here
    	
    	long ts = System.currentTimeMillis();
    	
    	// sleep some
    	try {
    		//sleep atleast 1 second but no more than 10 seconds
			java.util.concurrent.TimeUnit.SECONDS.sleep(new Random().nextInt(10) + 1);
		} catch (InterruptedException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
    	long tm = System.currentTimeMillis() - ts;
    	
        return "Hello World " + in + " took " + tm + "ms ";
    }

}
